Repository AY2021S1-CS2113T-W13-4/tp, pull requests merged in 2020-10, with the labels that each got.

#37 Fix bug related to file saving in wrong LocalDateTime formats
  src/main/java/seedu/lifeasier/commands/AddDeadlineCommand.java
  src/main/java/seedu/lifeasier/commands/AddEventCommand.java
  src/main/java/seedu/lifeasier/commands/AddLessonCommand.java
  src/main/java/seedu/lifeasier/storage/FileCommand.java
  src/main/java/seedu/lifeasier/storage/FileStorage.java
  src/main/java/seedu/lifeasier/storage/TaskStorage.java
  src/main/java/seedu/lifeasier/tasks/TaskList.java
  src/main/java/seedu/lifeasier/ui/Ui.java
Labels: type.Bug

#83 Update DG with individual component
  docs/DeveloperGuide.md
  docs/images/DeveloperGuide/StorageClassDiagram.png
  docs/images/DeveloperGuide/StorageLaunchSequenceDiagram.png
  docs/images/DeveloperGuide/StorageSaveSequenceDiagram.png
  src/main/java/seedu/lifeasier/parser/Parser.java
Labels: documentation

#87 Bug fixing and improvements to code
  src/main/java/seedu/lifeasier/parser/Parser.java
  src/main/java/seedu/lifeasier/storage/FileCommand.java
  src/main/java/seedu/lifeasier/storage/TaskStorage.java
  src/main/java/seedu/lifeasier/tasks/Deadline.java
  src/main/java/seedu/lifeasier/tasks/Event.java
  src/main/java/seedu/lifeasier/tasks/Lesson.java
  src/main/java/seedu/lifeasier/tasks/Task.java
  src/main/java/seedu/lifeasier/ui/Ui.java
  src/test/java/seedu/lifeasier/commands/FreeTimeCommandTest.java
  src/test/java/seedu/lifeasier/commands/SleepTimeCommandTest.java
  src/test/java/seedu/lifeasier/storage/FileCommandTest.java
  src/test/java/seedu/lifeasier/storage/TaskStorageTest.java
Labels: type.Bug, type.Enhancement

#86 Fix bug of empty last /param
  src/main/java/seedu/lifeasier/LifEasier.java
  src/main/java/seedu/lifeasier/commands/EditNotesCommand.java
  src/main/java/seedu/lifeasier/parser/Parser.java
  src/main/java/seedu/lifeasier/ui/Ui.java
Labels: type.Bug

#91 Update to UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/DeveloperGuide/Figure 4.4-1.png
  docs/images/DeveloperGuide/Figure 4.5-1.png
  docs/images/DeveloperGuide/Figure 4.5-2.png
Labels: documentation

#84 Update UG and DG with individual components
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/lifeasier/commands/DisplayScheduleCommand.java
  src/main/java/seedu/lifeasier/commands/EditDeadlineCommand.java
  src/main/java/seedu/lifeasier/commands/EditEventCommand.java
  src/main/java/seedu/lifeasier/commands/EditLessonCommand.java
  src/main/java/seedu/lifeasier/commands/UndoNoteCommand.java
  src/main/java/seedu/lifeasier/commands/UndoTaskCommand.java
  src/main/java/seedu/lifeasier/notes/NoteHistory.java
  src/main/java/seedu/lifeasier/tasks/TaskHistory.java
  src/main/java/seedu/lifeasier/ui/ScheduleUi.java
  src/main/java/seedu/lifeasier/ui/Ui.java
  src/test/java/seedu/lifeasier/tasks/TaskHistoryTest.java
Labels: documentation

#89 Fix bug causing tasks to not update properly
  src/main/java/seedu/lifeasier/commands/UndoTaskCommand.java
  src/main/java/seedu/lifeasier/tasks/Deadline.java
  src/main/java/seedu/lifeasier/tasks/Event.java
  src/main/java/seedu/lifeasier/tasks/Lesson.java
  src/main/java/seedu/lifeasier/tasks/Task.java
  src/main/java/seedu/lifeasier/tasks/TaskList.java
Labels: severity.Medium, type.Bug

#90 Add Daniel's components to UG and DG
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/images/DeveloperGuide/Figure3.2.4-1.jpg
  docs/images/DeveloperGuide/Figure4.8-1.jpg
  docs/images/DeveloperGuide/Figure4.8-2.jpg
  src/main/java/seedu/lifeasier/commands/EditDeadlineCommand.java
  src/main/java/seedu/lifeasier/commands/EditEventCommand.java
  src/main/java/seedu/lifeasier/commands/EditLessonCommand.java
Labels: documentation, priority.High, type.Task

#110 Fix deleteTask crashing on invalid input
  src/main/java/seedu/lifeasier/commands/DeleteTaskCommand.java
  src/main/java/seedu/lifeasier/parser/Parser.java
  src/main/java/seedu/lifeasier/ui/Ui.java
Labels: priority.Medium, type.Bug

#111 Fix bug for hourly highlight not showing up at 23:00
  src/main/java/seedu/lifeasier/LifEasier.java
  src/main/java/seedu/lifeasier/ui/TimetableUi.java
Labels: type.Bug

#109 Add Fairuz's UG components into UG and update DG
  docs/UserGuide.md
  docs/images/DeveloperGuide/Figure 4.2-1.1.png
  docs/images/DeveloperGuide/Figure 4.2-1.png
  docs/images/DeveloperGuide/Figure 4.3-1.png
Labels: documentation

#119 Updates to DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/DeveloperGuide/Figure 4.7-2.png
  docs/images/DeveloperGuide/StorageLaunchSequenceDiagram.png
Labels: documentation, type.Enhancement
