Repository AY2021S1-CS2113T-W13-4/tp, pull requests merged in 2020-11, with the labels that each got.

#115 Update some minor typos and mistakes in UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation, severity.Low

#166 Bug Fixing and Program Improvements
  src/main/java/seedu/lifeasier/ui/Ui.java
  src/test/java/seedu/lifeasier/commands/FreeTimeCommandTest.java
  src/test/java/seedu/lifeasier/commands/SleepTimeCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, type.Enhancement

#180 Add Fairuz's PPP
  docs/team/skyaxe97.md
Labels: documentation

#177 Add Edmund's PPP
  docs/team/edmundexe.md
  docs/team/johndoe.md
Labels: documentation

#172 Add Daniel's PPP
  docs/AboutUs.md
  docs/team/daniellimzj.md
Labels: documentation, type.Task

#173 Add Danzel's PPP
  docs/team/dojh111.md
  src/main/java/seedu/lifeasier/LifEasier.java
  src/main/java/seedu/lifeasier/model/notes/NoteHistory.java
  src/main/java/seedu/lifeasier/storage/FileStorage.java
  src/test/java/seedu/lifeasier/commands/FreeTimeCommandTest.java
  src/test/java/seedu/lifeasier/commands/SleepTimeCommandTest.java
Labels: documentation, type.Task

#174 Bug Fixing and Improvements for v2.1
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/lifeasier/commands/EditLessonCommand.java
  src/main/java/seedu/lifeasier/model/tasks/TaskList.java
  src/main/java/seedu/lifeasier/parser/Parser.java
  src/main/java/seedu/lifeasier/storage/FileArchive.java
  src/main/java/seedu/lifeasier/storage/FileCommand.java
  src/main/java/seedu/lifeasier/storage/NoteStorage.java
  src/main/java/seedu/lifeasier/storage/TaskStorage.java
  src/main/java/seedu/lifeasier/ui/SaveDelimiterException.java
  src/main/java/seedu/lifeasier/ui/Ui.java
  src/test/java/seedu/lifeasier/parser/ParserTest.java
  src/test/java/seedu/lifeasier/storage/FileCommandTest.java
  src/test/java/seedu/lifeasier/storage/NoteStorageTest.java
  src/test/java/seedu/lifeasier/storage/TaskStorageTest.java
Labels: documentation, type.Bug

#175 Bug Fixing and UGDG updates for v2.1
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/DeveloperGuide/Figure 4.6-1.png
  docs/images/DeveloperGuide/Figure 4.6-2.png
  src/main/java/seedu/lifeasier/LifEasier.java
  src/main/java/seedu/lifeasier/commands/DisplayScheduleCommand.java
  src/main/java/seedu/lifeasier/model/notes/NoteHistory.java
  src/main/java/seedu/lifeasier/model/tasks/TaskHistory.java
  src/main/java/seedu/lifeasier/parser/Parser.java
  src/main/java/seedu/lifeasier/ui/Ui.java
Labels: documentation, type.Bug

#179 Update UG and clarity of prompt
  docs/UserGuide.md
  src/main/java/seedu/lifeasier/parser/Parser.java
  src/main/java/seedu/lifeasier/ui/Ui.java
Labels: severity.Low, type.Enhancement

#181 Change all /time to /from
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/lifeasier/model/tasks/Deadline.java
  src/main/java/seedu/lifeasier/model/tasks/Event.java
  src/main/java/seedu/lifeasier/model/tasks/Lesson.java
  src/main/java/seedu/lifeasier/parser/Parser.java
  src/main/java/seedu/lifeasier/ui/Ui.java
  src/test/java/seedu/lifeasier/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: severity.Low, type.Bug

#182 Fix indexing error for delete and edit commands
  docs/images/DeveloperGuide/Figure 4.2-1.png
  docs/images/DeveloperGuide/Figure 4.3-1.png
  src/main/java/seedu/lifeasier/commands/DeleteTaskCommand.java
  src/main/java/seedu/lifeasier/commands/EditDeadlineCommand.java
  src/main/java/seedu/lifeasier/commands/EditEventCommand.java
  src/main/java/seedu/lifeasier/commands/EditLessonCommand.java
  src/main/java/seedu/lifeasier/model/tasks/TaskList.java
  src/main/java/seedu/lifeasier/parser/Parser.java
  src/main/java/seedu/lifeasier/ui/Ui.java
Labels: severity.Low, type.Bug

#169 Fix lesson updates and duplicates
  docs/AboutUs.md
  src/main/java/seedu/lifeasier/commands/AddDeadlineCommand.java
  src/main/java/seedu/lifeasier/commands/AddEventCommand.java
  src/main/java/seedu/lifeasier/commands/AddLessonCommand.java
  src/main/java/seedu/lifeasier/commands/FreeTimeCommand.java
  src/main/java/seedu/lifeasier/commands/HelpCommand.java
  src/main/java/seedu/lifeasier/commands/SleepTimeCommand.java
  src/main/java/seedu/lifeasier/model/notes/NoteCommandFunctions.java
  src/main/java/seedu/lifeasier/model/tasks/Deadline.java
  src/main/java/seedu/lifeasier/model/tasks/Event.java
  src/main/java/seedu/lifeasier/model/tasks/Lesson.java
  src/main/java/seedu/lifeasier/model/tasks/Task.java
  src/main/java/seedu/lifeasier/model/tasks/TaskDuplicateException.java
  src/main/java/seedu/lifeasier/model/tasks/TaskList.java
  src/main/java/seedu/lifeasier/model/tasks/TaskPastException.java
  src/main/java/seedu/lifeasier/parser/Parser.java
  src/main/java/seedu/lifeasier/storage/FileCommand.java
  src/main/java/seedu/lifeasier/storage/TaskStorage.java
  src/main/java/seedu/lifeasier/ui/Ui.java
  src/test/java/seedu/lifeasier/commands/FreeTimeCommandTest.java
  src/test/java/seedu/lifeasier/commands/SleepTimeCommandTest.java
  src/test/java/seedu/lifeasier/model/tasks/TaskListTest.java
  src/test/java/seedu/lifeasier/ui/ScheduleUiTest.java
Labels: severity.Medium, type.Bug

#170 Add table 1-1 and graphics to UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/UserGuide/post-it.png
  src/main/java/seedu/lifeasier/LifEasier.java
  src/main/java/seedu/lifeasier/commands/AddNotesCommand.java
  src/main/java/seedu/lifeasier/commands/DeleteNotesCommand.java
  src/main/java/seedu/lifeasier/commands/DeleteTaskCommand.java
  src/main/java/seedu/lifeasier/commands/DisplayScheduleCommand.java
  src/main/java/seedu/lifeasier/commands/EditDeadlineCommand.java
  src/main/java/seedu/lifeasier/commands/EditEventCommand.java
  src/main/java/seedu/lifeasier/commands/EditLessonCommand.java
  src/main/java/seedu/lifeasier/commands/EditNotesCommand.java
  src/main/java/seedu/lifeasier/commands/HelpCommand.java
  src/main/java/seedu/lifeasier/commands/ShowNotesCommand.java
  src/main/java/seedu/lifeasier/commands/SleepTimeCommand.java
  src/main/java/seedu/lifeasier/commands/UndoNoteCommand.java
  src/main/java/seedu/lifeasier/commands/UndoTaskCommand.java
  src/main/java/seedu/lifeasier/model/tasks/TaskList.java
  src/main/java/seedu/lifeasier/parser/Parser.java
  src/main/java/seedu/lifeasier/storage/TaskStorage.java
  src/main/java/seedu/lifeasier/ui/Ui.java
  src/test/java/seedu/lifeasier/commands/FreeTimeCommandTest.java
  src/test/java/seedu/lifeasier/commands/SleepTimeCommandTest.java
  src/test/java/seedu/lifeasier/commands/UndoTaskCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: documentation, severity.Low, type.Bug

#168 Fix consistency of printed messages using Ui class.
  src/main/java/seedu/lifeasier/commands/AddNotesCommand.java
  src/main/java/seedu/lifeasier/commands/DeleteNotesCommand.java
  src/main/java/seedu/lifeasier/commands/DeleteTaskCommand.java
  src/main/java/seedu/lifeasier/commands/DisplayScheduleCommand.java
  src/main/java/seedu/lifeasier/commands/EditDeadlineCommand.java
  src/main/java/seedu/lifeasier/commands/EditEventCommand.java
  src/main/java/seedu/lifeasier/commands/EditNotesCommand.java
  src/main/java/seedu/lifeasier/commands/FreeTimeCommand.java
  src/main/java/seedu/lifeasier/commands/HelpCommand.java
  src/main/java/seedu/lifeasier/commands/ShowNotesCommand.java
  src/main/java/seedu/lifeasier/parser/Parser.java
  src/main/java/seedu/lifeasier/storage/FileCommand.java
  src/main/java/seedu/lifeasier/storage/TaskStorage.java
  src/main/java/seedu/lifeasier/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: severity.Medium, type.Bug, type.Task

#186 Fix incorrect editing of task description when editing deadline/event
  src/main/java/seedu/lifeasier/commands/DeleteTaskCommand.java
  src/main/java/seedu/lifeasier/commands/EditDeadlineCommand.java
  src/main/java/seedu/lifeasier/commands/EditEventCommand.java
  src/main/java/seedu/lifeasier/commands/EditLessonCommand.java
  src/main/java/seedu/lifeasier/model/tasks/TaskList.java
  src/main/java/seedu/lifeasier/parser/Parser.java
  src/main/java/seedu/lifeasier/ui/Ui.java
Labels: severity.Low, type.Bug

#189 Bug Fixing and UI Improvements
  docs/UserGuide.md
  src/main/java/seedu/lifeasier/storage/FileCommand.java
  src/main/java/seedu/lifeasier/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: severity.Low, type.Bug

#188 Fix bug allowing negative recurrences when save file is edited
  src/main/java/seedu/lifeasier/model/tasks/TaskList.java
Labels: severity.Medium, type.Bug

#192 Minor changes to UG and DG
  docs/UserGuide.md
  docs/images/DeveloperGuide/Figure 4.9-1.png
  docs/images/DeveloperGuide/Figure 4.9-2.png
Labels: documentation

#194 Fix bugs in TaskHistory tests, minor UG updates
  docs/UserGuide.md
  docs/team/johan9se.md
  src/main/java/seedu/lifeasier/commands/DisplayScheduleCommand.java
  src/main/java/seedu/lifeasier/commands/UndoNoteCommand.java
  src/main/java/seedu/lifeasier/commands/UndoTaskCommand.java
  src/main/java/seedu/lifeasier/model/notes/NoteHistory.java
  src/main/java/seedu/lifeasier/model/tasks/TaskHistory.java
  src/main/java/seedu/lifeasier/model/tasks/TaskList.java
  src/test/java/seedu/lifeasier/commands/UndoTaskCommandTest.java
  src/test/java/seedu/lifeasier/model/tasks/TaskHistoryTest.java
Labels: documentation, type.Bug

#190 UG Updates
  docs/UserGuide.md
Labels: documentation

#191 Fix minor UI bugs
  src/main/java/seedu/lifeasier/commands/DisplayScheduleCommand.java
  src/main/java/seedu/lifeasier/ui/Ui.java
Labels: severity.Low, type.Bug

#196 Add ShowNotesCommand section into DG
  docs/DeveloperGuide.md
  docs/images/DeveloperGuide/Figure 4.10-1.png
  docs/images/DeveloperGuide/Figure 4.10-2.png
  docs/images/DeveloperGuide/Figure 4.6-1.png
  docs/images/DeveloperGuide/Figure 4.6-2.png
  docs/images/DeveloperGuide/Figure 4.7-1.png
  docs/images/DeveloperGuide/Figure 4.7-2.png
  docs/images/DeveloperGuide/Figure 4.8-1.png
  docs/images/DeveloperGuide/Figure 4.8-2.png
  docs/images/DeveloperGuide/Figure 4.9-1.png
Labels: documentation, priority.Medium

#195 Add Fairuz's DG changes
  docs/DeveloperGuide.md
  docs/images/DeveloperGuide/Figure 4.1-1.png
  docs/images/DeveloperGuide/Figure 4.2-1.png
  docs/images/DeveloperGuide/Figure 4.3-1.png
Labels: documentation, priority.Low

#199 Put finishing touches on UG
  docs/UserGuide.md
Labels: documentation

#198 Add JUnit tests for Fairuz's components
  src/main/java/seedu/lifeasier/commands/DeleteTaskCommand.java
  src/main/java/seedu/lifeasier/commands/EditDeadlineCommand.java
  src/main/java/seedu/lifeasier/commands/EditEventCommand.java
  src/main/java/seedu/lifeasier/commands/EditLessonCommand.java
  src/main/java/seedu/lifeasier/model/tasks/TaskHistory.java
  src/main/java/seedu/lifeasier/model/tasks/TaskList.java
  src/main/java/seedu/lifeasier/parser/Parser.java
  src/main/java/seedu/lifeasier/ui/Ui.java
  src/test/java/seedu/lifeasier/commands/AddDeadlineCommandTest.java
  src/test/java/seedu/lifeasier/commands/AddEventCommandTest.java
  src/test/java/seedu/lifeasier/commands/AddLessonCommandTest.java
  src/test/java/seedu/lifeasier/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/lifeasier/commands/EditDeadlineCommandTest.java
  src/test/java/seedu/lifeasier/commands/EditEventCommandTest.java
  src/test/java/seedu/lifeasier/commands/EditLessonCommandTest.java
  src/test/java/seedu/lifeasier/model/tasks/DeadlineTest.java
  src/test/java/seedu/lifeasier/model/tasks/EventTest.java
  src/test/java/seedu/lifeasier/model/tasks/LessonTest.java
  src/test/java/seedu/lifeasier/model/tasks/TaskListTest.java
Labels: priority.Medium

#201 Fix note testing outputs
  src/test/java/seedu/lifeasier/commands/AddNotesCommandTest.java
  src/test/java/seedu/lifeasier/commands/DeleteNotesCommandTest.java
  src/test/java/seedu/lifeasier/commands/EditNotesCommandTest.java
  src/test/java/seedu/lifeasier/commands/ShowNotesCommandTest.java
Labels: severity.Medium, type.Bug

#200 Fix DG UML diagrams
  docs/images/DeveloperGuide/Figure 4.1-1.png
  docs/images/DeveloperGuide/Figure 4.2-1.png
  docs/images/DeveloperGuide/Figure 4.3-1.png
Labels: documentation

#202 Edit Developer Guide based on group walkthrough
  docs/DeveloperGuide.md
Labels: documentation

#203 Fix bug related to single input commands
  src/main/java/seedu/lifeasier/parser/Parser.java
  src/test/java/seedu/lifeasier/parser/ParserTest.java
Labels: severity.Medium, type.Bug

#208 Update DG Diagrams
  docs/images/DeveloperGuide/Figure 3.1-2.png
  docs/images/DeveloperGuide/Figure 4.10-1.png
  docs/images/DeveloperGuide/Figure 4.10-2.png
Labels: documentation

#209 Add task saving after startup and updating
  src/main/java/seedu/lifeasier/LifEasier.java
  src/test/java/seedu/lifeasier/model/tasks/TaskListTest.java
Labels: severity.Low, type.Bug

#210 Update Daniel's PPP
  docs/AboutUs.md
  docs/team/daniellimzj.md
Labels: documentation

#204 Update UG examples and DG diagrams
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/DeveloperGuide/Figure 4.7-1.png
  docs/images/DeveloperGuide/Figure 4.7-2.png
  docs/images/DeveloperGuide/Figure 4.9-1.png
  src/main/java/seedu/lifeasier/parser/Parser.java
Labels: documentation

#205 Fix DG diagrams and PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/DeveloperGuide/Figure 4.4-1.png
  docs/images/DeveloperGuide/Figure 4.5-1.png
  docs/images/DeveloperGuide/Figure 4.5-2.png
  docs/images/DeveloperGuide/Figure 4.6-1.png
  docs/team/edmundexe.md
Labels: documentation, severity.Low

#211 Update Fairuz's PPP
  docs/team/skyaxe97.md
Labels: documentation

#207 Updates to PPP and DG Images
  docs/images/DeveloperGuide/Figure 4.8-2.png
  docs/images/DeveloperGuide/StorageClassDiagram.png
  docs/images/DeveloperGuide/StorageSaveSequenceDiagram.png
  docs/team/dojh111.md
Labels: documentation

#206 Increase file read defensiveness
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/lifeasier/commands/AddNotesCommand.java
  src/main/java/seedu/lifeasier/commands/DeleteNotesCommand.java
  src/main/java/seedu/lifeasier/commands/EditNotesCommand.java
  src/main/java/seedu/lifeasier/commands/UndoNoteCommand.java
  src/main/java/seedu/lifeasier/parser/Parser.java
  src/main/java/seedu/lifeasier/storage/FileCommand.java
  src/main/java/seedu/lifeasier/storage/FileStorage.java
  src/main/java/seedu/lifeasier/storage/LogicalTimeException.java
  src/main/java/seedu/lifeasier/storage/TaskStorage.java
  src/main/java/seedu/lifeasier/storage/UnequalSaveDateException.java
  src/main/java/seedu/lifeasier/ui/TimetableUi.java
  src/main/java/seedu/lifeasier/ui/Ui.java
  src/test/java/seedu/lifeasier/storage/TaskStorageTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, type.Bug

#213 Change titles, update links, update formatting
  README.md
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/team/daniellimzj.md
  docs/team/dojh111.md
  docs/team/edmundexe.md
  docs/team/johan9se.md
  docs/team/skyaxe97.md
Labels: documentation
